### ISSUE TITLE
Request: webassembly/emscripten tutorial

### ISSUE THREAD

**Issue by Eelis** [OGStudio/openscenegraph-cross-platform-guide#1]
Thanks for making these great tutorials! Is a webassembly/emscripten tutorial also planned?

**Comment by kornerr** [comment]
Sure! Currently I work on iOS sample. I plan to do Web (Emscripten) part next month, in June.

**Comment by Eelis** [comment]
Ok, awesome!

**Comment by kornerr** [comment]
The web tutorial is finally ready: https://github.com/OGStudio/openscenegraph-cross-platform-guide/tree/master/1.10.SampleWeb

And here's how the result looks like (the link also is in the end of the tutorial): https://ogstudio.github.io/openscenegraph-cross-platform-guide/

I've checked it under Linux and iOS, both work fine (however, I can't rotate the cube under iOS).

**Comment by Eelis** [comment]
This is awesome, thanks a ton!
