### ISSUE TITLE
Failure to install OpenSG 3.4.1 on OS X 10.12.6 using CMake 3.9.1

### ISSUE THREAD

**Issue by ruthaylett** [OGStudio/openscenegraph-cross-platform-guide#3]
![screen shot 2017-09-06 at 14 31 04](https://user-images.githubusercontent.com/31699326/30117074-174188e0-9317-11e7-9768-e57a65f5f58c.png)

Error message is: Error in configuration process, project files may be invalid

**Comment by ruthaylett** [comment]
But does work as advertised on OS X 11.4 up to the build. Then the build fails:

/Users/ruthaylett/p/OpenSceneGraph/src/osgPlugins/vrml/ConvertToVRML.cpp:564:7: error: 
      no member named 'get' in 'osg::Matrixf'
  mat.get(quat);
  ~~~ ^
1 error generated.

**Comment by kornerr** [comment]
Hi. I'm going to re-check the build process this month, so it will take some time.

Meanwhile, if you only want OpenSceneGraph for macOS, you can get it from brew: `brew install open-scene-graph`. I recently used it, worked fine for me.

**Comment by kornerr** [comment]
Hi.

As of today, I did not attempt to build OpenSceneGraph manually because brew's packages were enough for me. And even enough to distribute macOS build: http://opengamestudio.org/mahjong-techdemo1-gameplay.html

I assume everyone should prefer brew's packages for macOS, that's why I'm closing the issue now.

If anyone has specific needs to build OpenSceneGraph manually for macOS, please, feel free to reopen this issue or create a new one.

**Comment by kornerr** [comment]
Using brew is different from what tutorial does, so instead I should verify OSG build under macOS High Sierra.

**Comment by kornerr** [comment]
Ok. I've finally spent time to build OpenSceneGraph from sources under macOS. It works fine for me.

Here is a full list of versions of the tools I used:
* **macOS**: Sierra, 10.12.6 (16G1212)
* **Xcode**: 9.2 (9C40b)
* **CMake**: 3.11.0
* **OpenSceneGraph**: git commit id `1d4f6c254388f10ced11b67429cd12cb5ad5fcf9`, 2018-04-17

However, I've noticed you tried to build VRML, which I don't have. Looks like you have a problem with VRML plugin. I'm afraid I don't have expertise to help with VRML plugin.

If you find a fix for VRML plugin, please, post here to let others know. Thanks.

PS: If you don't need VRML plugin, you can safely ignore it.
