### ISSUE TITLE
Add jpeg/png/etc support to android application

### ISSUE THREAD

**Issue by deedoc** [OGStudio/openscenegraph-cross-platform-guide#4]
Hi there! Thanks for such a great tutorial!
But could you show how to add images (and may be other plugins) support for android builds in order to open models with textures like [this one from openscenegraph/OpenSceneGraph-Data repository](https://github.com/openscenegraph/OpenSceneGraph-Data/blob/master/clock.osgt)?

**Comment by kornerr** [comment]
Hi!
I currently research the use of PNG images, so once this is done (2-3 months), I'll update the article(s) and this issue.

**Comment by deedoc** [comment]
Sounds so great! Could you give me a direction? May be i can help. I able to
build and run osg on android thanks to your tutorial!

**Comment by kornerr** [comment]
Yeah. You may search for 'native android png' to find libpng ports for Android. Something like this one: https://github.com/julienr/libpng-android
Build it and link with it. That's my plan for now :)

**Comment by kornerr** [comment]
Hi. I've created the example on how to use PNG image (embedded into application) across platforms, including Android: https://github.com/OGStudio/openscenegraph-cross-platform-examples/tree/master/02.TextureImage
