### ISSUE TITLE
Openscenegraph 3.3.1 support for OSGGuideApp.

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [OGStudio/openscenegraph-cross-platform-guide#5]
Hi,

I followed the guide to build the OSGGuideApp for the latest openscengraph(master from github) and it works flawlessly.

Although when i just replace the "openscenegraph" folder with the **3.3.1** version it does not work.

It complains with the following error on gradle. 
https://gyazo.com/2cdec5890c7b57b38b6742ac78fd15c5

Build error shows this:
`org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.`

I am new to android build. We wanted to get our osg based desktop app on android. I am well versed with cmake. 

_But, I am not able to understand how the android build system here and cmake are connected._

Any help on how can i proceed to fix this will be great.

**Comment by kornerr** [comment]
Is there any specific reason to use OSG 3.3.1?

**Comment by SrinivasPrabhu794** [comment]
Hi,
Yes. We wanted to upgrade from 3.3.1 but there was some restructuring done in osg in the higher versions. Esp the ones where the Geode/Drawable are inheriting from Group node. These changes hurt our massive app in its current state. So we have to stick to 3.3.1.

**Comment by kornerr** [comment]
Once I touch Android this month or next one, I'll have a look at building OSG 3.3.1 for Android.

**Comment by SrinivasPrabhu794** [comment]
@kornerr  thank you :)

**Comment by kornerr** [comment]
I tried to give 3.3.1 a shot, however, I get CMake error that 'ANDROID_3RD_PARTY()' does not exist.
How did you fix the error?

**Comment by SrinivasPrabhu794** [comment]
i dont think i reached even till that point. I get stuck at step one with the above mentioned error

`org.gradle.api.ProjectConfigurationException:`

**Comment by SrinivasPrabhu794** [comment]
Do u think there is any hope of fixing it for 3.3.1 ?

**Comment by kornerr** [comment]
Well, there are two problems with 3.3.1:

* it's a developer release (not stable one)
* it's 4 years old (and gets older every day without receiving fixes)

The 'ANDROID_3RD_PARTY()' missing is one of the errors that got fixed some time later, I can't even remember seeing this error before. May be because I was using stable at the time.

What's the exact OSG version that broke Geode/Drawable for you?

**Comment by SrinivasPrabhu794** [comment]
Hi Michael,

 I think the 3.4.0 series onwards it starts to break, with the geode/drawable issue.

**Comment by kornerr** [comment]
Did you try 3.2.3 (the latest stable before 3.4.0) or 3.3.9 (the latest developer release before 3.4.0)?

**Comment by SrinivasPrabhu794** [comment]
Not yet. Do the stable versions do not have the android issues? I have seen 3.3.9 and it has the geode/drawable changes.

**Comment by kornerr** [comment]
Stable versions should be definitely preferred if you stick to some version.
3.3.9 is probably where 3.4.0 came from, so yeah, 3.3.9 isn't the version to use.

You should try 3.2.3 then.

**Comment by SrinivasPrabhu794** [comment]
ok, i will try 3.2.3 and let you know.

**Comment by kornerr** [comment]
Any luck?

**Comment by kornerr** [comment]
Hey. Any updates on the issue?

**Comment by SrinivasPrabhu794** [comment]
Hello Kornerr,

We have decided to use the latest version of osg for our work as the support is good. Thanks for your concern :) 👍 If there is any other issue I will update on this thread.

**Comment by kornerr** [comment]
Great.
